version: '2'
services:
  mgr8_test_db:
    image: percona
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "mgr8_db"
    volumes:
      - ./bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql

#  mgr8:
#	build: .
#	volumes:
#	 - .:/opt/mgr8
#	depends_on:
#	 - mgr8_test_db
